version: "3.9"

services:
  api:
    build: .
    command: uvicorn server.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////app/zap_dashboard.db
      ZAP_AUTH_ENCRYPTION_KEY: h47OImZGM-IqQk4sGM8j_IeOc5YB-uWdAoTQnHTxN9A
      ZAP_NODE_NAME: zap1
    volumes:
      - .:/app
    depends_on:
      - zap1
      - zap2
    networks:
      - appnet

  worker:
    build: .
    command: python worker/main.py
    environment:
      DATABASE_URL: sqlite:////app/zap_dashboard.db
      ZAP_AUTH_ENCRYPTION_KEY: h47OImZGM-IqQk4sGM8j_IeOc5YB-uWdAoTQnHTxN9A
      ZAP_NODE_URL: http://zap1:8080
    volumes:
      - .:/app
    depends_on:
      - zap1
      - zap2
    networks:
      - appnet

  zap1:
    image: zaproxy/zap-stable
    container_name: zap1
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8080
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config api.key=changeme123
    expose:
      - "8080"
    networks:
      - appnet

  zap2:
    image: zaproxy/zap-stable
    container_name: zap2
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8080
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config api.key=changeme123
    expose:
      - "8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
